openapi: "3.0.3"
info:
  title: "Groovy Music API"
  version: "1.0.0"
  description: "API для музыкального сервиса Groovy"
servers:
  - url: "http://127.0.0.1:8080/api/v1"
    description: "Бэк для музыкального сервиса"

tags:
  - name: Authentication
    description: "Endpoints for auth"
    x-displayName: "Authentification"
  - name: Tracks
    description: "Endpoints for tracks"
    x-displayName: "Tracks"
  - name: Albums
    description: "Endpoints for albums"
    x-displayName: "Albums"

paths:
  /auth/register:
    post:
      tags: [Authentication]
      summary: "Регистрация нового пользователя"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: "Успешная регистрация"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "400":
          description: "Невалидные данные"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/login:
    post:
      tags: [Authentication]
      summary: "Авторизация пользователя"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: "Успешный вход"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: "Неверные учетные данные"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tracks:
    get:
      tags: [Tracks]
      summary: "Получить все треки"
      responses:
        "200":
          description: "Список треков"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Track"

  /tracks/{id}:
    get:
      tags: [Tracks]
      summary: "Получить трек по ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Трек"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        "404":
          description: "Не найден"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /albums:
    get:
      tags: [Albums]
      summary: "Получить все альбомы"
      responses:
        "200":
          description: "Список альбомов"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Album"
        "500":
          description: "Внутренняя ошибка сервера"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /albums/{id}:
    get:
      tags: [Albums]
      summary: "Получить альбом по ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Альбом"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Album"
        "404":
          description: "Не найден"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Внутренняя ошибка сервера"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /albums/artist/{artist}:
    get:
      tags: [Albums]
      summary: "Получить альбомы по имени исполнителя"
      parameters:
        - name: artist
          in: path
          required: true
          schema:
            type: string
          example: "Queen"
      responses:
        "200":
          description: "Список альбомов исполнителя"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Album"
        "400":
          description: "Неверный запрос"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Внутренняя ошибка сервера"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /albums/search:
    get:
      tags: [Albums]
      summary: "Поиск альбомов по названию"
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          example: "Night"
          description: "Поисковый запрос"
      responses:
        "200":
          description: "Список найденных альбомов"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Album"
        "400":
          description: "Неверный запрос"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Внутренняя ошибка сервера"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /albums/genre/{genre}:
    get:
      tags: [Albums]
      summary: "Получить альбомы по жанру"
      parameters:
        - name: genre
          in: path
          required: true
          schema:
            type: string
          example: "Rock"
      responses:
        "200":
          description: "Список альбомов выбранного жанра"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Album"
        "400":
          description: "Неверный запрос"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Внутренняя ошибка сервера"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    RegisterRequest:
      type: object
      required: [email, password, username]
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          format: password
          minLength: 8
          example: "securePassword123"
        username:
          type: string
          minLength: 3
          example: "music_lover"

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          format: password
          example: "securePassword123"

    AuthResponse:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/UserDto"
        token:
          type: string
          description: "JWT токен для аутентификации"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    UserDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        email:
          type: string
          example: "user@example.com"
        username:
          type: string
          example: "music_lover"

    Track:
      type: object
      properties:
        id:
          type: string
          example: "track_123"
        title:
          type: string
          example: "My Favorite Song"
        artist:
          type: string
          example: "Popular Artist"
        duration:
          type: integer
          example: 180
        albumId:
          type: string
          example: "album_456"
        storagePath:
          type: string
          example: "tracks/album_456/track_123.mp3"
        coverUrl:
          type: string
          example: "https://example.com/covers/album_456.jpg"
        likesCount:
          type: integer
          example: 42
        playsCount:
          type: integer
          example: 1000

    Album:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "A Night At Opera"
        artist:
          type: string
          example: "Queen"
        coverUrl:
          type: string
          example: "https://cdn-images.dzcdn.net/images/cover/201607ab9cd92a1f977659c7c524cadf/0x1900-000000-80-0-0.jpg"
        createdAt:
          type: string
          example: "1975"
        genre:
          type: string
          example: "Rock"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid credentials"
        message:
          type: string
          example: "Password must be at least 8 characters long"